### ISSUE TITLE
运行项目报错web3swift

### ISSUE THREAD

**Issue by qq992326916** [OpenIMSDK/Open-IM-iOS-Demo#1]
pod完项目后报错web3swift xcode版本13.1

**Comment by qq992326916** [comment]
No such module ‘web3swift'

**Comment by frcc00** [comment]
pod install --repo-update
试试

**Comment by qq992326916** [comment]
![image](https://user-images.githubusercontent.com/39426176/143555212-580ab296-f782-4bbe-a192-9dce5b98eb01.png)
