### ISSUE TITLE
模拟器一直提示这个问题,我的项目都跑不起模拟器直接卡死

### ISSUE THREAD

**Issue by QiuYeHong90** [OpenIMSDK/Open-IM-iOS-Demo#10]
Warning: Error creating LLDB target at path '/Users/ray/Library/Developer/Xcode/DerivedData/OpenIMSDKUIKit-dblwgzevguaectgkuvdijjwmqhwd/Build/Products/Debug-iphonesimulator/OpenIMSDKUIKit_Example.app'- using an empty LLDB target which can cause slow memory reads from remote devices: the specified architecture 'arm64-*-*' is not compatible with 'x86_64-apple-ios11.0.0-simulator' in '/Users/ray/Library/Developer/Xcode/DerivedData/OpenIMSDKUIKit-dblwgzevguaectgkuvdijjwmqhwd/Build/Products/Debug-iphonesimulator/OpenIMSDKUIKit_Example.app/OpenIMSDKUIKit_Example'

**Comment by std-s** [comment]
尝试调整编译设置。
