### ISSUE TITLE
error  Undefined symbol: _String

### ISSUE THREAD

**Issue by yanglhan** [openimsdk/open-im-ios-demo#11]

**Comment by yanglhan** [comment]
Undefined symbols for architecture arm64:
  "_String", referenced from:
      -[OIMManager(Message) setAppBadge:onSuccess:onFailure:] in OpenIMSDK(OIMManager+Message.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by std-s** [comment]
升级sdk。

**Comment by yanglhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by std-s** [comment]
No feedback for a long time, please close this question first.

**Comment by yanglhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
