### ISSUE TITLE
Bug: <describe the error>

### ISSUE THREAD

**Issue by PeteriOS1234** [openimsdk/open-im-ios-demo#12]
### What happened?

After starting the application for the first time and logging in, restarting the xcode application will cause a crash.
<img width="1052" alt="截屏2023-09-14 15 26 22" src="https://github.com/openimsdk/open-im-ios-demo/assets/93307356/30b97335-f98c-401a-9027-fd39cf5f4fe0">

### What did you expect to happen?

I'm wondering what might be causing this, is there something missing in my code? I am using OpenimSDK(v3.2.0)

### How can we reproduce it (as minimally and precisely as possible)?

I'm wondering what might be causing this, is there something missing in my code? I am using OpenimSDK(v3.2.0)

### Anything else we need to know?

I'm wondering what might be causing this, is there something missing in my code? I am using OpenimSDK(v3.2.0)

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by std-s** [comment]
hi, Try updating SDK3.3.0 to see if the problem still exists.
