### ISSUE TITLE
[Other]: <give this problem a name>

### ISSUE THREAD

**Issue by tianyu9090** [openimsdk/open-im-ios-demo#19]
### What would you like to share?

注册时，接口报错
输入参数：{"areaCode":"+86","platform":1,"usedFor":3,"phoneNumber":"18228641425"}
Printing description of errMsg:
▿ Optional<String>
  - some : "ServerInternalError"

### Additional information

注册时，接口报错
输入参数：{"areaCode":"+86","platform":1,"usedFor":3,"phoneNumber":"18228641425"}
Printing description of errMsg:
▿ Optional<String>
  - some : "ServerInternalError"

**Comment by std-s** [comment]
Hi, check the server deployment.
