### ISSUE TITLE
[FEATURE REQUEST] After downloading and installing the iOS version of the test demo, it prompts that its integrity cannot be verified

### ISSUE THREAD

**Issue by morgen620** [openimsdk/open-im-ios-demo#24]
### Why this feature?

     ios版本的测试demo下载安装后提示无法验证其完整性，无法测试完整的ios功能

### Suggested Solution

是否可以提供ipa包，供用户自行签名测试

**Comment by std-s** [comment]
Hi, can you provide the UDID to the official for testing.

**Comment by morgen620** [comment]
> Hi, can you provide the UDID to the official for testing.

e5dcf35972d149c08cc98c4a11384a44e407726a

**Comment by morgen620** [comment]
@std-s  e5dcf35972d149c08cc98c4a11384a44e407726a

**Comment by morgen620** [comment]
@std-s Can you provide a test IPA file?

**Comment by std-s** [comment]
@morgen620  Hi, we no longer provide individual forms to obtain ipa files.

**Comment by std-s** [comment]
Close this question first.
