### ISSUE TITLE
[BUG] Command SwiftCompile failed with a nonzero exit code

### ISSUE THREAD

**Issue by zisequkuai** [openimsdk/open-im-ios-demo#26]
### OpenIM Server Version

laster

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

An error occurred while compiling the iOS demo. The error message is as follows:
![1](https://github.com/user-attachments/assets/8f04b420-1876-4839-8530-fc127303a00b)

**Comment by YanjieZhao** [comment]
the same problem,Xcode 16

**Comment by std-s** [comment]
Hi, if you want to adapt to Xcode 16, you can make changes according to the official suggestions of [ChatLayout](https://github.com/ekazaev/ChatLayout) and [Alamofire](https://github.com/Alamofire/Alamofire).

**Comment by std-s** [comment]
Close this question first.
