### ISSUE TITLE
In the conversation list, two identical group chats appear

### ISSUE THREAD

**Issue by xiaoyao20084321** [openimsdk/open-im-ios-demo#7]
问题：会话列表中，会出现两个一模一样的群聊
![image](https://user-images.githubusercontent.com/10344550/186296975-7ce2da72-ce69-43ec-8cad-be2f399dd796.png)
复现步骤：
1、邀请好友加入群
2、加入成功后，在群里发条消息
3、返回到会话列表页面即会出现

**Comment by std-s** [comment]
No feedback for a long time, please close this question first.
