### ISSUE TITLE
When will there be an Objective-C version of the demo?

### ISSUE THREAD

**Issue by sonwa** [openimsdk/open-im-ios-demo#8]
啥时候有Objective-C版Demo？

**Comment by zziacgl** [comment]
同求OC版本demo

**Comment by std-s** [comment]
暂时没有计划。

**Comment by jimckylin** [comment]
sdk 2.3.4.1报错 InsertMessage()@36: InsertMessage failed: sql: database is closed]，是什么错误？

**Comment by 1786305952** [comment]
> 啥时候有Objective-C版Demo？

请问你这边有OC版本了吗
